    drop database if exists concord;
    drop user if exists'coordenador'@'localhost';

    create database if not exists concord;

    use concord;


    create user if not exists 'coordenador'@'localhost' identified by 'fatec123';

    grant all privileges on concord.* to 'coordenador'@'localhost';

    flush privileges;

    CREATE TABLE professor (
        id INT AUTO_INCREMENT PRIMARY KEY,
        nome VARCHAR(100) NOT NULL,
        email VARCHAR(100) NOT NULL UNIQUE,
        telefone VARCHAR(20),
        carga_horaria INT DEFAULT 11,
        matricula VARCHAR(20) NOT NULL UNIQUE,
        status INT DEFAULT 1
    );

    CREATE TABLE disciplina (
        id INT AUTO_INCREMENT PRIMARY KEY,
        nome VARCHAR(100) NOT NULL
    );

    CREATE TABLE curso (
        id INT AUTO_INCREMENT PRIMARY KEY,
        nome VARCHAR(100) NOT NULL,
        sigla VARCHAR(10),
        duracao INT,
        descricao TEXT,
        coordenador_id INT,
        FOREIGN KEY (coordenador_id) REFERENCES professor(id)
    );
    
     CREATE TABLE disciplina_professor (
    id INT AUTO_INCREMENT PRIMARY KEY,
    professor_id INT,
    disciplina_id INT NOT NULL,
	FOREIGN KEY (disciplina_id) REFERENCES disciplina(id),
	FOREIGN KEY (professor_id) REFERENCES professor(id)
    );

    CREATE TABLE aula (
        id INT AUTO_INCREMENT PRIMARY KEY,
        dia VARCHAR(20) NOT NULL,
        horario_inicio TIME NOT NULL,
        horario_termino TIME NOT NULL,
        disci_prof_id INT NOT NULL,
        FOREIGN KEY (disci_prof_id) REFERENCES disciplina_professor(id)
    );

    CREATE TABLE turma (
        id INT AUTO_INCREMENT PRIMARY KEY,
        modalidade VARCHAR(50),
        turno VARCHAR(50),
        periodo VARCHAR(50),
        curso_id INT,
        FOREIGN KEY (curso_id) REFERENCES curso(id)
    );

    CREATE TABLE turma_aula (
        id INT AUTO_INCREMENT PRIMARY KEY,
        turma_id INT NOT NULL,
        aula_id INT NOT NULL,
        FOREIGN KEY (turma_id) REFERENCES turma(id) ON DELETE CASCADE,
        FOREIGN KEY (aula_id) REFERENCES aula(id) ON DELETE CASCADE
    );
    
 INSERT INTO professor (nome, email, telefone, matricula, status, carga_horaria) VALUES
('Adriana da Silva Jacinto', 'adriana.da@senac.local', '1198001000', 'MAT0001', 1, 9),
('Adilson Lucimar Simões', 'adilson.lucimar@senac.local', '1198001001', 'MAT0002', 1, 9),
('Alfred Makoto Kabayama', 'alfred.makoto@senac.local', '1198001002', 'MAT0003', 1, 9),
('Ana Cecília Rodrigues Medeiros', 'ana.cecilia@senac.local', '1198001003', 'MAT0004', 1, 11),
('Ana Maria Pereira', 'ana.maria@senac.local', '1198001004', 'MAT0005', 1, 9),
('Andrea Marques de Carvalho', 'andrea.marques@senac.local', '1198001005', 'MAT0006', 1, 11),
('Antônio Egydio São Thiago Graça', 'antonio.egydio@senac.local', '1198001006', 'MAT0007', 1, 10),
('Antônio Josivaldo Dantas Filho', 'antonio.josivaldo@senac.local', '1198001007', 'MAT0008', 1, 9),
('Antônio Wellington Sales Rios', 'antonio.wellington@senac.local', '1198001008', 'MAT0009', 1, 11),
('Arlindo Strottmann', 'arlindo.strottmann@senac.local', '1198001009', 'MAT0010', 1, 9),
('Bruno Peruchi Trevisan', 'bruno.peruchi@senac.local', '1198001010', 'MAT0011', 1, 9),
('Carlos Augusto Lombardi Garcia', 'carlos.augusto@senac.local', '1198001011', 'MAT0012', 1, 9),
('Carlos Eduardo Bastos', 'carlos.eduardo@senac.local', '1198001012', 'MAT0013', 1, 10),
('Carlos Henrique Loureiro Feichas', 'carlos.henrique@senac.local', '1198001013', 'MAT0014', 1, 10),
('Carlos Lineu de Faria e Alves', 'carlos.lineu@senac.local', '1198001014', 'MAT0015', 1, 10),
('Cássia Cristina Bordini Cintra', 'cassia.cristina@senac.local', '1198001015', 'MAT0016', 1, 10),
('Celso de Oliveira', 'celso.de@senac.local', '1198001016', 'MAT0017', 1, 11),
('Cícero Soares da Silva', 'cicero.soares@senac.local', '1198001017', 'MAT0018', 1, 10),
('Cláudio Etelvino de Lima', 'claudio.etelvino@senac.local', '1198001018', 'MAT0019', 1, 9),
('Danielle Cristina de Morais Amorim', 'danielle.cristina@senac.local', '1198001019', 'MAT0020', 1, 10),
('Dawilmar Guimarães de Araújo', 'dawilmar.guimaraes@senac.local', '1198001020', 'MAT0021', 1, 10),
('Dercy Felix da Silva', 'dercy.felix@senac.local', '1198001021', 'MAT0022', 1, 11),
('Diogo Branquinho Ramos', 'diogo.branquinho@senac.local', '1198001022', 'MAT0023', 1, 9),
('Edmar de Queiroz Figueiredo', 'edmar.de@senac.local', '1198001023', 'MAT0024', 1, 9),
('Eduardo Clemente Medeiros', 'eduardo.clemente@senac.local', '1198001024', 'MAT0025', 1, 9),
('Eduardo de Castro Faustino Coelho', 'eduardo.de@senac.local', '1198001025', 'MAT0026', 1, 10),
('Eduardo Sakaue', 'eduardo.sakaue@senac.local', '1198001026', 'MAT0027', 1, 11),
('Eliane Penha Mergulhão Dias', 'eliane.penha@senac.local', '1198001027', 'MAT0028', 1, 11),
('Emanuel Mineda Carneiro', 'emanuel.mineda@senac.local', '1198001028', 'MAT0029', 1, 9),
('Érico Luciano Pagotto', 'erico.luciano@senac.local', '1198001029', 'MAT0030', 1, 11),
('Fabiana Eloisa Passador', 'fabiana.eloisa@senac.local', '1198001030', 'MAT0031', 1, 10),
('Fabiano Sabha Walczak', 'fabiano.sabha@senac.local', '1198001031', 'MAT0032', 1, 9),
('Fábio José Santos de Oliveira', 'fabio.jose@senac.local', '1198001032', 'MAT0033', 1, 11),
('Fábio Luciano Pagotto', 'fabio.luciano@senac.local', '1198001033', 'MAT0034', 1, 9),
('Fernando Masanori Ashikaga', 'fernando.masanori@senac.local', '1198001034', 'MAT0035', 1, 11),
('Geraldo José Lombardi de Souza', 'geraldo.jose@senac.local', '1198001035', 'MAT0036', 1, 11),
('Gerson Carlos Favalli', 'gerson.carlos@senac.local', '1198001036', 'MAT0037', 1, 11),
('Gerson da Penha Neto', 'gerson.da@senac.local', '1198001037', 'MAT0038', 1, 11),
('Giuliano Araujo Bertoti', 'giuliano.araujo@senac.local', '1198001038', 'MAT0039', 1, 10),
('Guaraci Lima de Moraes', 'guaraci.lima@senac.local', '1198001039', 'MAT0040', 1, 10),
('Heide Heloise Bernardi', 'heide.heloise@senac.local', '1198001040', 'MAT0041', 1, 11),
('Herculano Camargo Ortiz', 'herculano.camargo@senac.local', '1198001041', 'MAT0042', 1, 9),
('Hudson Alberto Bode', 'hudson.alberto@senac.local', '1198001042', 'MAT0043', 1, 10),
('Jean Carlos Lourenço Costa', 'jean.carlos@senac.local', '1198001043', 'MAT0044', 1, 9),
('Joares Lidovino dos Reis', 'joares.lidovino@senac.local', '1198001044', 'MAT0045', 1, 11),
('Jorge Tadao Matsushima', 'jorge.tadao@senac.local', '1198001045', 'MAT0046', 1, 11),
('José Jaetis Rosario', 'jose.jaetis@senac.local', '1198001046', 'MAT0047', 1, 9),
('José Walmir Gonçalves Duque', 'jose.walmir@senac.local', '1198001047', 'MAT0048', 1, 10),
('Juliana Forin Pasquini Martinez', 'juliana.forin@senac.local', '1198001048', 'MAT0049', 1, 11),
('Leonidas Lopes de Melo', 'leonidas.lopes@senac.local', '1198001049', 'MAT0050', 1, 9),
('Lise Virgínia Vieira de Azevedo', 'lise.virginia@senac.local', '1198001050', 'MAT0051', 1, 10),
('Lucas Giovanetti', 'lucas.giovanetti@senac.local', '1198001051', 'MAT0052', 1, 11),
('Lucas Gonçalves Nadalete', 'lucas.goncalves@senac.local', '1198001052', 'MAT0053', 1, 9),
('Luiz Alberto Nolasco Fonseca', 'luiz.alberto@senac.local', '1198001053', 'MAT0054', 1, 10),
('Luiz Antonio Tozi', 'luiz.antonio@senac.local', '1198001054', 'MAT0055', 1, 11),
('Manoel Roman Filho', 'manoel.roman@senac.local', '1198001055', 'MAT0056', 1, 11),
('Marcos Allan Ferreira Gonçalves', 'marcos.allan@senac.local', '1198001056', 'MAT0057', 1, 9),
('Marcos da Silva e Souza', 'marcos.da@senac.local', '1198001057', 'MAT0058', 1, 9),
('Marcos Paulo Lobo de Candia', 'marcos.paulo@senac.local', '1198001058', 'MAT0059', 1, 10),
('Marluce Gavião Sacramento Dias', 'marluce.gaviao@senac.local', '1198001059', 'MAT0060', 1, 9),
('Martin Lugones', 'martin.lugones@senac.local', '1198001060', 'MAT0061', 1, 10),
('Marcus Vinícius do Nascimento', 'marcus.vinicius@senac.local', '1198001061', 'MAT0062', 1, 10),
('Maria Aparecida Miranda de Souza', 'maria.aparecida@senac.local', '1198001062', 'MAT0063', 1, 11),
('Maria Goreti Lopes Cepinho', 'maria.goreti@senac.local', '1198001063', 'MAT0064', 1, 11),
('Nanci de Oliveira', 'nanci.de@senac.local', '1198001064', 'MAT0065', 1, 9),
('Newton Eizo Yamada', 'newton.eizo@senac.local', '1198001065', 'MAT0066', 1, 11),
('Nilo Castro dos Santos', 'nilo.castro@senac.local', '1198001066', 'MAT0067', 1, 11),
('Nilo Jeronimo Vieira', 'nilo.jeronimo@senac.local', '1198001067', 'MAT0068', 1, 10),
('Reinaldo Fagundes dos Santos', 'reinaldo.fagundes@senac.local', '1198001068', 'MAT0069', 1, 10),
('Reinaldo Gen Ichiro Arakaki', 'reinaldo.gen@senac.local', '1198001069', 'MAT0070', 1, 10),
('Reinaldo Viveiros Carraro', 'reinaldo.viveiros@senac.local', '1198001070', 'MAT0071', 1, 10),
('Renato Galvão da Silveira Mussi', 'renato.galvao@senac.local', '1198001071', 'MAT0072', 1, 10),
('Renata Cristiane Fusverk da Silva', 'renata.cristiane@senac.local', '1198001072', 'MAT0073', 1, 9),
('Rita de Cássia M. Sales Contini', 'rita.de@senac.local', '1198001073', 'MAT0074', 1, 11),
('Rodrigo Elias Pereira', 'rodrigo.elias@senac.local', '1198001074', 'MAT0075', 1, 10),
('Rogério Benedito de Andrade', 'rogerio.benedito@senac.local', '1198001075', 'MAT0076', 1, 10),
('Roque Antonio de Moura', 'roque.antonio@senac.local', '1198001076', 'MAT0077', 1, 11),
('Rubens Barreto da Silva', 'rubens.barreto@senac.local', '1198001077', 'MAT0078', 1, 9),
('Samuel Martin Maresti', 'samuel.martin@senac.local', '1198001078', 'MAT0079', 1, 11),
('Santiago Martin Lugones', 'santiago.martin@senac.local', '1198001079', 'MAT0080', 1, 11),
('Sanzara Nhiaaia Jardim Costa Hassmann', 'sanzara.nhiaaia@senac.local', '1198001080', 'MAT0081', 1, 10),
('Teresinha de Fátima Nogueira', 'teresinha.de@senac.local', '1198001081', 'MAT0082', 1, 11),
('Vera Lúcia Monteiro', 'vera.lucia@senac.local', '1198001082', 'MAT0083', 1, 10),
('Viviane Ribeiro de Siqueira', 'viviane.ribeiro@senac.local', '1198001083', 'MAT0084', 1, 9),
('Wagner Luiz de Oliveira', 'wagner.luiz@senac.local', '1198001084', 'MAT0085', 1, 10);

INSERT INTO curso (nome, sigla, duracao, descricao, coordenador_id) VALUES
('Análise e Desenvolvimento de Sitemas', 'ADS', 5, 'O curso de Análise e Desenvolvimento de Sitemas prepara profissionais com competências técnicas e práticas para atuar na área.', 65),
('Banco de Dados', 'BD', 6, 'O curso de Banco de Dados prepara profissionais com competências técnicas e práticas para atuar na área.', 32),
('Desenvolvimento de Software Multiplataforma', 'DSM', 8, 'O curso de Desenvolvimento de Software Multiplataforma prepara profissionais com competências técnicas e práticas para atuar na área.', 37),
('Gestão de Produção Industrial', 'GPI', 7, 'O curso de Gestão de Produção Industrial prepara profissionais com competências técnicas e práticas para atuar na área.', 25),
('Logística', 'L', 7, 'O curso de Logística prepara profissionais com competências técnicas e práticas para atuar na área.', 19),
('Logística', 'L', 4, 'O curso de Logística prepara profissionais com competências técnicas e práticas para atuar na área.', 32),
('Manufatura Avançada', 'MA', 5, 'O curso de Manufatura Avançada prepara profissionais com competências técnicas e práticas para atuar na área.', 6),
('Manutenção de Aeronaves', 'MA', 8, 'O curso de Manutenção de Aeronaves prepara profissionais com competências técnicas e práticas para atuar na área.', 9),
('Projetos de Estruturas Aeronáuticas', 'PEA', 4, 'O curso de Projetos de Estruturas Aeronáuticas prepara profissionais com competências técnicas e práticas para atuar na área.', 3);

INSERT INTO disciplina (nome) VALUES
('Administração de Banco de Dados'),
('Administração Geral'),
('Algoritmos e Lógica de Programação'),
('Arquitetura e Organização de Computadores'),
('Banco de Dados'),
('Banco de Dados – Relacional'),
('Banco de Dados - Não Relacional'),
('Computação em Nuvem I'),
('Computação em Nuvem II'),
('Comunicação e Expressão'),
('Comunicação Oral e Escrita'),
('Comércio Exterior'),
('Comércio Exterior e Logística'),
('Contabilidade'),
('Contabilidade Gerencial'),
('Custos e Tarifas Logísticas'),
('Custos Industriais'),
('Desenho'),
('Economia'),
('Economia e Finanças'),
('Economia e Finanças Empresariais'),
('Embalagens e Unitização'),
('Engenharia de Software I'),
('Engenharia de Software II'),
('Engenharia de Software III'),
('Ergonomia'),
('Espanhol I'),
('Espanhol II'),
('Estatística'),
('Estatística Aplicada'),
('Estatística Aplicada à Gestão'),
('Ética e Direito Empresarial'),
('Ética e Responsabilidade Profissional'),
('Ética Profissional e Patente'),
('Experiência do Usuário'),
('Fundamentos da Comunicação e Expressão'),
('Fundamentos da Comunicação Empresarial'),
('Fundamentos de Administração'),
('Fundamentos de Automação Industrial'),
('Fundamentos de Gestão da Qualidade'),
('Fundamentos de Gestão de Projetos'),
('Fundamentos de Matemática Financeira'),
('Gestão Ambiental Aplicada'),
('Gestão da Cadeia de Suprimentos'),
('Gestão da Produção Aplicada'),
('Gestão da Produção e Operações'),
('Gestão de Equipes'),
('Gestão de Marketing e Vendas'),
('Gestão de Pessoas'),
('Gestão de Projetos'),
('Gestão de Projetos Logísticos'),
('Gestão de Transporte de Cargas e Roteirização'),
('Gestão e Governança de Tecnologia da Informação'),
('Gestão Financeira'),
('Gestão Tributária nas Operações Logísticas'),
('Higiene e Segurança do Trabalho'),
('Informática'),
('Informática Aplicada à Logística'),
('Inglês I'),
('Inglês II'),
('Inglês III'),
('Inglês IV'),
('Inglês V'),
('Inglês VI'),
('Inglês para Logística I'),
('Inglês para Logística II'),
('Inglês para Logística III'),
('Inglês para Logística IV'),
('Inteligência Artificial'),
('Interação Humano-Computador'),
('Introdução à Contabilidade'),
('Jogos de Empresas'),
('Laboratório de Banco de Dados'),
('Laboratório de Desenvolvimento em BD I'),
('Laboratório de Desenvolvimento em BD II'),
('Laboratório de Desenvolvimento em BD III'),
('Laboratório de Desenvolvimento em BD IV'),
('Laboratório de Desenvolvimento em BD V'),
('Laboratório de Desenvolvimento em BD VI'),
('Laboratório de Desenvolvimento Multiplataforma'),
('Laboratório de Engenharia de Software'),
('Laboratório de Hardware'),
('Liderança e Empreendedorismo'),
('Linguagem de Programação'),
('Linguagem de Programação I'),
('Linguagem de Programação II'),
('Logística Empresarial'),
('Logística Verde'),
('Matemática Aplicada'),
('Matemática Discreta'),
('Matemática Financeira'),
('Mecânica'),
('Metodologia da Pesquisa Científica'),
('Metodologia da Pesquisa Científico-Tecnológica'),
('Metodologias de Desenvolvimento de Software'),
('Metodologias de Manutenção de Aeronaves'),
('Métodos para a Produção do Conhecimento'),
('Métodos Quantitativos de Gestão'),
('Modalidade e Intermodalidade'),
('Movimentação e Armazenagem'),
('Navegação Interior e Portos Marítimos'),
('Planejamento, Programação e Controle da Produção (PPCP)'),
('Planejamento Estratégico I'),
('Planejamento Estratégico II'),
('Processos de Produção'),
('Programação Avançada de Banco de Dados'),
('Programação de Scripts'),
('Programação em Microinformática'),
('Programação Linear e Aplicações'),
('Programação Orientada a Objetos'),
('Programação para Dispositivos Móveis'),
('Programação para Dispositivos Móveis I'),
('Programação para Dispositivos Móveis II'),
('Projeto de Fábrica'),
('Projeto de Produto I'),
('Projeto de Produto II'),
('Projeto de Trabalho de Graduação I'),
('Projeto de Trabalho de Graduação II'),
('Projeto Integrador Aplicado à Logística I'),
('Projeto Integrador Aplicado à Logística II'),
('Projeto Integrador Aplicado à Logística III'),
('Projeto Integrador Aplicado à Logística IV'),
('Projeto Integrador em Gestão da Produção Industrial I'),
('Projeto Integrador em Gestão da Produção Industrial II'),
('Projeto Integrador em GPI III'),
('Projeto Interdisciplinar VI'),
('Qualidade e Testes de Software'),
('Redes de Computadores'),
('Segurança da Informação'),
('Simulação Aplicada à Produção'),
('Simulação em Logística'),
('Sistemas de Informação'),
('Sistemas de Movimentação e Transporte'),
('Sistemas Operacionais I'),
('Sistemas Operacionais II'),
('Sociedade e Tecnologia'),
('Tecnologia da Informação Aplicada à Gestão de Operações e Processos'),
('Tecnologia da Informação Aplicada à Logística'),
('Tecnologia da Produção Industrial'),
('Tecnologia dos Transportes'),
('Tópicos Avançados em Banco de Dados'),
('Tópicos Especiais em Informática'),
('Transportes de Cargas Especiais'),
('Transporte Aéreo');

INSERT INTO turma (modalidade, turno, periodo, curso_id) VALUES
('Presencial', 'Matutino', '1º', 1),
('Presencial', 'Matutino', '2º', 1),
('Presencial', 'Matutino', '3º', 1),
('Presencial', 'Matutino', '4º', 1),
('Presencial', 'Matutino', '5º', 1),
('Presencial', 'Vespertino', '1º', 1),
('Presencial', 'Vespertino', '2º', 1),
('Presencial', 'Vespertino', '3º', 1),
('Presencial', 'Vespertino', '4º', 1),
('Presencial', 'Vespertino', '5º', 1),
('Presencial', 'Noturno', '1º', 1),
('Presencial', 'Noturno', '2º', 1),
('Presencial', 'Noturno', '3º', 1),
('Presencial', 'Noturno', '4º', 1),
('Presencial', 'Noturno', '5º', 1),
('EAD', 'Matutino', '1º', 1),
('EAD', 'Matutino', '2º', 1),
('EAD', 'Matutino', '3º', 1),
('EAD', 'Matutino', '4º', 1),
('EAD', 'Matutino', '5º', 1),
('EAD', 'Vespertino', '1º', 1),
('EAD', 'Vespertino', '2º', 1),
('EAD', 'Vespertino', '3º', 1),
('EAD', 'Vespertino', '4º', 1),
('EAD', 'Vespertino', '5º', 1),
('EAD', 'Noturno', '1º', 1),
('EAD', 'Noturno', '2º', 1),
('EAD', 'Noturno', '3º', 1),
('EAD', 'Noturno', '4º', 1),
('EAD', 'Noturno', '5º', 1),
('Presencial', 'Matutino', '1º', 2),
('Presencial', 'Matutino', '2º', 2),
('Presencial', 'Matutino', '3º', 2),
('Presencial', 'Matutino', '4º', 2),
('Presencial', 'Matutino', '5º', 2),
('Presencial', 'Matutino', '6º', 2),
('Presencial', 'Vespertino', '1º', 2),
('Presencial', 'Vespertino', '2º', 2),
('Presencial', 'Vespertino', '3º', 2),
('Presencial', 'Vespertino', '4º', 2),
('Presencial', 'Vespertino', '5º', 2),
('Presencial', 'Vespertino', '6º', 2),
('Presencial', 'Noturno', '1º', 2),
('Presencial', 'Noturno', '2º', 2),
('Presencial', 'Noturno', '3º', 2),
('Presencial', 'Noturno', '4º', 2),
('Presencial', 'Noturno', '5º', 2),
('Presencial', 'Noturno', '6º', 2),
('EAD', 'Matutino', '1º', 2),
('EAD', 'Matutino', '2º', 2),
('EAD', 'Matutino', '3º', 2),
('EAD', 'Matutino', '4º', 2),
('EAD', 'Matutino', '5º', 2),
('EAD', 'Matutino', '6º', 2),
('EAD', 'Vespertino', '1º', 2),
('EAD', 'Vespertino', '2º', 2),
('EAD', 'Vespertino', '3º', 2),
('EAD', 'Vespertino', '4º', 2),
('EAD', 'Vespertino', '5º', 2),
('EAD', 'Vespertino', '6º', 2),
('EAD', 'Noturno', '1º', 2),
('EAD', 'Noturno', '2º', 2),
('EAD', 'Noturno', '3º', 2),
('EAD', 'Noturno', '4º', 2),
('EAD', 'Noturno', '5º', 2),
('EAD', 'Noturno', '6º', 2),
('Presencial', 'Matutino', '1º', 3),
('Presencial', 'Matutino', '2º', 3),
('Presencial', 'Matutino', '3º', 3),
('Presencial', 'Matutino', '4º', 3),
('Presencial', 'Matutino', '5º', 3),
('Presencial', 'Matutino', '6º', 3),
('Presencial', 'Matutino', '7º', 3),
('Presencial', 'Matutino', '8º', 3),
('Presencial', 'Vespertino', '1º', 3),
('Presencial', 'Vespertino', '2º', 3),
('Presencial', 'Vespertino', '3º', 3),
('Presencial', 'Vespertino', '4º', 3),
('Presencial', 'Vespertino', '5º', 3),
('Presencial', 'Vespertino', '6º', 3),
('Presencial', 'Vespertino', '7º', 3),
('Presencial', 'Vespertino', '8º', 3),
('Presencial', 'Noturno', '1º', 3),
('Presencial', 'Noturno', '2º', 3),
('Presencial', 'Noturno', '3º', 3),
('Presencial', 'Noturno', '4º', 3),
('Presencial', 'Noturno', '5º', 3),
('Presencial', 'Noturno', '6º', 3),
('Presencial', 'Noturno', '7º', 3),
('Presencial', 'Noturno', '8º', 3),
('EAD', 'Matutino', '1º', 3),
('EAD', 'Matutino', '2º', 3),
('EAD', 'Matutino', '3º', 3),
('EAD', 'Matutino', '4º', 3),
('EAD', 'Matutino', '5º', 3),
('EAD', 'Matutino', '6º', 3),
('EAD', 'Matutino', '7º', 3),
('EAD', 'Matutino', '8º', 3),
('EAD', 'Vespertino', '1º', 3),
('EAD', 'Vespertino', '2º', 3),
('EAD', 'Vespertino', '3º', 3),
('EAD', 'Vespertino', '4º', 3),
('EAD', 'Vespertino', '5º', 3),
('EAD', 'Vespertino', '6º', 3),
('EAD', 'Vespertino', '7º', 3),
('EAD', 'Vespertino', '8º', 3),
('EAD', 'Noturno', '1º', 3),
('EAD', 'Noturno', '2º', 3),
('EAD', 'Noturno', '3º', 3),
('EAD', 'Noturno', '4º', 3),
('EAD', 'Noturno', '5º', 3),
('EAD', 'Noturno', '6º', 3),
('EAD', 'Noturno', '7º', 3),
('EAD', 'Noturno', '8º', 3),
('Presencial', 'Matutino', '1º', 4),
('Presencial', 'Matutino', '2º', 4),
('Presencial', 'Matutino', '3º', 4),
('Presencial', 'Matutino', '4º', 4),
('Presencial', 'Matutino', '5º', 4),
('Presencial', 'Matutino', '6º', 4),
('Presencial', 'Matutino', '7º', 4),
('Presencial', 'Vespertino', '1º', 4),
('Presencial', 'Vespertino', '2º', 4),
('Presencial', 'Vespertino', '3º', 4),
('Presencial', 'Vespertino', '4º', 4),
('Presencial', 'Vespertino', '5º', 4),
('Presencial', 'Vespertino', '6º', 4),
('Presencial', 'Vespertino', '7º', 4),
('Presencial', 'Noturno', '1º', 4),
('Presencial', 'Noturno', '2º', 4),
('Presencial', 'Noturno', '3º', 4),
('Presencial', 'Noturno', '4º', 4),
('Presencial', 'Noturno', '5º', 4),
('Presencial', 'Noturno', '6º', 4),
('Presencial', 'Noturno', '7º', 4),
('EAD', 'Matutino', '1º', 4),
('EAD', 'Matutino', '2º', 4),
('EAD', 'Matutino', '3º', 4),
('EAD', 'Matutino', '4º', 4),
('EAD', 'Matutino', '5º', 4),
('EAD', 'Matutino', '6º', 4),
('EAD', 'Matutino', '7º', 4),
('EAD', 'Vespertino', '1º', 4),
('EAD', 'Vespertino', '2º', 4),
('EAD', 'Vespertino', '3º', 4),
('EAD', 'Vespertino', '4º', 4),
('EAD', 'Vespertino', '5º', 4),
('EAD', 'Vespertino', '6º', 4),
('EAD', 'Vespertino', '7º', 4),
('EAD', 'Noturno', '1º', 4),
('EAD', 'Noturno', '2º', 4),
('EAD', 'Noturno', '3º', 4),
('EAD', 'Noturno', '4º', 4),
('EAD', 'Noturno', '5º', 4),
('EAD', 'Noturno', '6º', 4),
('EAD', 'Noturno', '7º', 4),
('Presencial', 'Matutino', '1º', 5),
('Presencial', 'Matutino', '2º', 5),
('Presencial', 'Matutino', '3º', 5),
('Presencial', 'Matutino', '4º', 5),
('Presencial', 'Matutino', '5º', 5),
('Presencial', 'Matutino', '6º', 5),
('Presencial', 'Matutino', '7º', 5),
('Presencial', 'Vespertino', '1º', 5),
('Presencial', 'Vespertino', '2º', 5),
('Presencial', 'Vespertino', '3º', 5),
('Presencial', 'Vespertino', '4º', 5),
('Presencial', 'Vespertino', '5º', 5),
('Presencial', 'Vespertino', '6º', 5),
('Presencial', 'Vespertino', '7º', 5),
('Presencial', 'Noturno', '1º', 5),
('Presencial', 'Noturno', '2º', 5),
('Presencial', 'Noturno', '3º', 5),
('Presencial', 'Noturno', '4º', 5),
('Presencial', 'Noturno', '5º', 5),
('Presencial', 'Noturno', '6º', 5),
('Presencial', 'Noturno', '7º', 5),
('EAD', 'Matutino', '1º', 5),
('EAD', 'Matutino', '2º', 5),
('EAD', 'Matutino', '3º', 5),
('EAD', 'Matutino', '4º', 5),
('EAD', 'Matutino', '5º', 5),
('EAD', 'Matutino', '6º', 5),
('EAD', 'Matutino', '7º', 5),
('EAD', 'Vespertino', '1º', 5),
('EAD', 'Vespertino', '2º', 5),
('EAD', 'Vespertino', '3º', 5),
('EAD', 'Vespertino', '4º', 5),
('EAD', 'Vespertino', '5º', 5),
('EAD', 'Vespertino', '6º', 5),
('EAD', 'Vespertino', '7º', 5),
('EAD', 'Noturno', '1º', 5),
('EAD', 'Noturno', '2º', 5),
('EAD', 'Noturno', '3º', 5),
('EAD', 'Noturno', '4º', 5),
('EAD', 'Noturno', '5º', 5),
('EAD', 'Noturno', '6º', 5),
('EAD', 'Noturno', '7º', 5),
('Presencial', 'Matutino', '1º', 6),
('Presencial', 'Matutino', '2º', 6),
('Presencial', 'Matutino', '3º', 6),
('Presencial', 'Matutino', '4º', 6),
('Presencial', 'Matutino', '5º', 6),
('Presencial', 'Vespertino', '1º', 6),
('Presencial', 'Vespertino', '2º', 6),
('Presencial', 'Vespertino', '3º', 6),
('Presencial', 'Vespertino', '4º', 6),
('Presencial', 'Vespertino', '5º', 6),
('Presencial', 'Noturno', '1º', 6),
('Presencial', 'Noturno', '2º', 6),
('Presencial', 'Noturno', '3º', 6),
('Presencial', 'Noturno', '4º', 6),
('Presencial', 'Noturno', '5º', 6),
('EAD', 'Matutino', '1º', 6),
('EAD', 'Matutino', '2º', 6),
('EAD', 'Matutino', '3º', 6),
('EAD', 'Matutino', '4º', 6),
('EAD', 'Matutino', '5º', 6),
('EAD', 'Vespertino', '1º', 6),
('EAD', 'Vespertino', '2º', 6),
('EAD', 'Vespertino', '3º', 6),
('EAD', 'Vespertino', '4º', 6),
('EAD', 'Vespertino', '5º', 6),
('EAD', 'Noturno', '1º', 6),
('EAD', 'Noturno', '2º', 6),
('EAD', 'Noturno', '3º', 6),
('EAD', 'Noturno', '4º', 6),
('EAD', 'Noturno', '5º', 6),
('Presencial', 'Matutino', '1º', 7),
('Presencial', 'Matutino', '2º', 7),
('Presencial', 'Matutino', '3º', 7),
('Presencial', 'Matutino', '4º', 7),
('Presencial', 'Matutino', '5º', 7),
('Presencial', 'Matutino', '6º', 7),
('Presencial', 'Matutino', '7º', 7),
('Presencial', 'Matutino', '8º', 7),
('Presencial', 'Vespertino', '1º', 7),
('Presencial', 'Vespertino', '2º', 7),
('Presencial', 'Vespertino', '3º', 7),
('Presencial', 'Vespertino', '4º', 7),
('Presencial', 'Vespertino', '5º', 7),
('Presencial', 'Vespertino', '6º', 7),
('Presencial', 'Vespertino', '7º', 7),
('Presencial', 'Vespertino', '8º', 7),
('Presencial', 'Noturno', '1º', 7),
('Presencial', 'Noturno', '2º', 7),
('Presencial', 'Noturno', '3º', 7),
('Presencial', 'Noturno', '4º', 7),
('Presencial', 'Noturno', '5º', 7),
('Presencial', 'Noturno', '6º', 7),
('Presencial', 'Noturno', '7º', 7),
('Presencial', 'Noturno', '8º', 7),
('EAD', 'Matutino', '1º', 7),
('EAD', 'Matutino', '2º', 7),
('EAD', 'Matutino', '3º', 7),
('EAD', 'Matutino', '4º', 7),
('EAD', 'Matutino', '5º', 7),
('EAD', 'Matutino', '6º', 7),
('EAD', 'Matutino', '7º', 7),
('EAD', 'Matutino', '8º', 7),
('EAD', 'Vespertino', '1º', 7),
('EAD', 'Vespertino', '2º', 7),
('EAD', 'Vespertino', '3º', 7),
('EAD', 'Vespertino', '4º', 7),
('EAD', 'Vespertino', '5º', 7),
('EAD', 'Vespertino', '6º', 7),
('EAD', 'Vespertino', '7º', 7),
('EAD', 'Vespertino', '8º', 7),
('EAD', 'Noturno', '1º', 7),
('EAD', 'Noturno', '2º', 7),
('EAD', 'Noturno', '3º', 7),
('EAD', 'Noturno', '4º', 7),
('EAD', 'Noturno', '5º', 7),
('EAD', 'Noturno', '6º', 7),
('EAD', 'Noturno', '7º', 7),
('EAD', 'Noturno', '8º', 7),
('Presencial', 'Matutino', '1º', 8),
('Presencial', 'Matutino', '2º', 8),
('Presencial', 'Matutino', '3º', 8),
('Presencial', 'Matutino', '4º', 8),
('Presencial', 'Vespertino', '1º', 8),
('Presencial', 'Vespertino', '2º', 8),
('Presencial', 'Vespertino', '3º', 8),
('Presencial', 'Vespertino', '4º', 8),
('Presencial', 'Noturno', '1º', 8),
('Presencial', 'Noturno', '2º', 8),
('Presencial', 'Noturno', '3º', 8),
('Presencial', 'Noturno', '4º', 8),
('EAD', 'Matutino', '1º', 8),
('EAD', 'Matutino', '2º', 8),
('EAD', 'Matutino', '3º', 8),
('EAD', 'Matutino', '4º', 8),
('EAD', 'Vespertino', '1º', 8),
('EAD', 'Vespertino', '2º', 8),
('EAD', 'Vespertino', '3º', 8),
('EAD', 'Vespertino', '4º', 8),
('EAD', 'Noturno', '1º', 8),
('EAD', 'Noturno', '2º', 8),
('EAD', 'Noturno', '3º', 8),
('EAD', 'Noturno', '4º', 8);
